Repository wrappid/styles, pull requests merged in 2024-03, with the labels that each got.

#55 enhancement: wrappid data context fix
  package/ConfigProvider.tsx
  package/StylesProvider.tsx
  package/context/WrappidContext.ts
  package/context/WrappidSyncer.tsx
  package/context/wrappidReducer.ts
  package/index.ts
  package/styledComponents/DefaultSCStyles.ts
  package/theme/cgpt.mui-theme.conf.json
Labels: bug

#56 feat(core): :sparkles: add styles for AspectRation
  package/utility/DefaultUtilityStyles.ts
  package/utility/UtilityClasses.ts
Labels: enhancement

#59 enhancement: header in attribution script
  ATTRIBUTIONS.md
  package/styledComponents/DefaultSCStyles.ts
  scripts/attributions.gen.js
Labels: enhancement

#61 chore(config): :lock: fix runtime security issues
  package-lock.json
Labels: security

#63 fix: :bug: fontsize of corelink is removed
  package/styledComponents/DefaultSCStyles.ts
Labels: bugfix

#65 enhancement: replace getConfigurationObject with WrappidData
  package/StyleUtil.ts
  package/context/WrappidContext.ts
  package/context/WrappidSyncer.tsx
  package/helper/helper.ts
  package/index.ts
  package/styledComponents/DefaultSCStyles.ts
Labels: enhancement

#67 bugfix: :bug: fix eslint pr guardrails
  .github/workflows/pr-guardrails.yml
  package/styledComponents/DefaultSCStyles.ts
Labels: bugfix

#68 enhancement: added aspect ratio for samsung galaxy fold
  .github/workflows/pr-guardrails.yml
  CHANGELOG.md
  package-lock.json
  package.json
  package/package-lock.json
  package/package.json
  package/styledComponents/DefaultSCStyles.ts
  package/utility/UtilityClasses.ts
Labels: enhancement

#69 enhancement: added aspect ratio for samsung galaxy fold
  package/utility/DefaultUtilityStyles.ts
  package/utility/UtilityClasses.ts
Labels: enhancement

#70 feat(core): :fire: data syncer related changes
  package/context/WrappidContext.ts
  package/context/WrappidSyncer.tsx
  package/context/wrappidAction.ts
  package/context/wrappidReducer.ts
  package/index.ts
Labels: enhancement

#74 bug fixed for bg dotted background styles and a text styles css
  package/utility/DefaultUtilityStyles.ts
  package/utility/UtilityClasses.ts
Labels: bugfix

#75 enhancement: themes related styles changes
  package/StylesProvider.tsx
Labels: enhancement

#76 feat(global): :sparkles: added different bg-grid styles added different bg-grid styles in utilityClasses
  package/utility/DefaultUtilityStyles.ts
  package/utility/UtilityClasses.ts
Labels: enhancement

#77 merge: Development into main
  CHANGELOG.md
  package-lock.json
  package.json
  package/StylesProvider.tsx
  package/context/WrappidContext.ts
  package/context/WrappidSyncer.tsx
  package/context/wrappidAction.ts
  package/context/wrappidReducer.ts
  package/index.ts
  package/package-lock.json
  package/package.json
  package/utility/DefaultUtilityStyles.ts
  package/utility/UtilityClasses.ts
Labels: enhancement

#78 styles for font-weight, line-height and word-spacing
  package/utility/DefaultUtilityStyles.ts
  package/utility/UtilityClasses.ts
Labels: enhancement

#79 fix(global): :bug: added Important tag to background Grey
  package/utility/DefaultUtilityStyles.ts
Labels: bugfix
