Repository wrappid/styles, pull requests merged in 2024-02, with the labels that each got.

#39 bugfix: styles files needs to be export as default
  ATTRIBUTIONS.md
  package.json
  package/StylesProvider.tsx
  package/base/BaseStyle.ts
  package/index.ts
  package/package.json
  package/styledComponents/DefaultSCStyles.ts
  package/styledComponents/LargeSCStyles.ts
  package/styledComponents/MediumSCStyles.ts
  package/styledComponents/SmallSCStyles.ts
  package/styledComponents/XLargeSCStyles.ts
  package/styledComponents/XXLargeSCStyles.ts
  package/utility/DefaultUtilityStyles.ts
  package/utility/LargeUtilityStyles.ts
  package/utility/MediumUtilityStyles.ts
  package/utility/SmallUtilityStyles.ts
  package/utility/XLargeUtilityStyles.ts
  package/utility/XXLargeUtilityStyles.ts
Labels: enhancement

#41 enhancement: linear gradient utility classes with styles
  package/theme/theme.ts
  package/utility/DefaultUtilityStyles.ts
  package/utility/UtilityClasses.ts
Labels: enhancement

#43 feat: :sparkles: create instances of different Corestyles
  package/StylesProvider.tsx
Labels: bug, enhancement

#46 fix(core): :bug: theme properties not changing issue resolved
  package/StylesProvider.tsx
  package/base/BaseStyle.ts
  package/context/WrappidContext.ts
Labels: bug

#49 enhancement: pr gaurdrails fix and update package.json cadet to tilde
  .github/workflows/pr-guardrails.yml
  .gitignore
  package-lock.json
  package.json
  package/styledComponents/DefaultSCStyles.ts
Labels: dependencies, bugfix

#51 fix(core): :bug: added Important tag to bgTransparent
  package/utility/DefaultUtilityStyles.ts
Labels: bugfix
