Repository wrappid/styles, pull requests merged in 2024-08, with the labels that each got.

#103 feat(core): 🔥 Adding list styles package in styles package #101
  package/utility/DefaultUtilityStyles.ts
  package/utility/UtilityClasses.ts
Labels: enhancement

#106 fix(core): :bug: add important to backgound in DefaultUtilityStyles
  package/utility/DefaultUtilityStyles.ts
Labels: bug

#108 docs(global): :memo: add basic necessary informations
  README.md
Labels: documentation
