Repository wrappid/styles, pull requests merged in 2024-01, with the labels that each got.

#17 docs: 🔒 license added
  LICENSE
Labels: documentation

#22 linting issue resolved
  .eslintrc.js
  package/ConfigProvider.tsx
  package/StyleUtil.ts
  package/StylesProvider.tsx
  package/base/BaseStyle.ts
  package/base/ThemeManager.ts
  package/base/contants.ts
  package/config/constants.ts
  package/helper/helper.ts
  package/index.ts
  package/styledComponents/DefaultSCStyles.ts
  package/styledComponents/LargeSCStyles.ts
  package/styledComponents/MediumSCStyles.ts
  package/styledComponents/SmallSCStyles.ts
  package/styledComponents/StyledComponentsClasses.ts
  package/styledComponents/XLargeSCStyles.ts
  package/styledComponents/XXLargeSCStyles.ts
  package/theme/theme.ts
  package/theme/themeType.ts
  package/theme/themeUtil.ts
  package/utility/DefaultUtilityStyles.ts
  package/utility/MediumUtilityStyles.ts
Labels: bug, cleanup

#25 refactor(global): :sparkles: addes PX tag to borders
  package/utility/DefaultUtilityStyles.ts
Labels: bug

#29 enhancement: context syncer
  ATTRIBUTIONS.md
  package.json
  package/context/WrappidContext.ts
  package/context/WrappidSyncer.tsx
  package/context/wrappidReducer.ts
  package/index.ts
  package/package.json
Labels: enhancement

#27 padding-x or px issue resolved and Important tag added to background color
  package/utility/DefaultUtilityStyles.ts
Labels: bug

#32 Merge development into main
  package-lock.json
  package.json
  package/context/WrappidContext.ts
  package/context/WrappidSyncer.tsx
  package/context/wrappidReducer.ts
  package/index.ts
  package/package-lock.json
  package/package.json
  package/utility/DefaultUtilityStyles.ts
Labels: enhancement

#33 refactor: typo fixed for constants file
  ATTRIBUTIONS.md
  package.json
  package/base/constants.ts
  package/index.ts
  package/package.json
  package/styledComponents/DefaultSCStyles.ts
  package/styledComponents/SmallSCStyles.ts
  package/utility/DefaultUtilityStyles.ts
  package/utility/LargeUtilityStyles.ts
  package/utility/MediumUtilityStyles.ts
  package/utility/SmallUtilityStyles.ts
  package/utility/XLargeUtilityStyles.ts
  package/utility/XXLargeUtilityStyles.ts
Labels: bug

#35 fix(core): :art: theme related issue fix
  package/base/BaseStyle.ts
  package/context/WrappidContext.ts
  package/context/WrappidSyncer.tsx
  package/theme/theme.ts
  package/theme/themeType.ts
Labels: bug, enhancement

#37 fix(global): :bug: removed spaces from the keys of theme and themeType
  package/context/WrappidSyncer.tsx
  package/theme/theme.ts
  package/theme/themeType.ts
Labels: bug
